//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Caas_ProjectTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public int ProjectID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string ProjectName { get; set; }
        public Nullable<int> StatusID { get; set; }
        public string OfferAmount { get; set; }
        public string DurationMonths { get; set; }
        public Nullable<System.DateTime> ExpectedStart { get; set; }
        public Nullable<System.DateTime> ExpectedFinish { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<int> ProjectProbability { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual StatusList StatusList { get; set; }
    }
}
